import { css } from '@/styled-system/css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const containerClass = css({ display: 'flex', minH: 'full_vh', bg: 'blueberry.2', color: 'gray.13' })
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className={containerClass}>{children}</div>
      </body>
    </html>
  )
}
