name: "Setup Project"
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v3
      with:
        version: ${{ env.PNPM_VERSION }}
        run_install: false

    - uses: actions/setup-node@v4
      with:
        node-version: "20.x"
        registry-url: "https://registry.npmjs.org"
        cache: "pnpm"
        cache-dependency-path: "./pnpm-lock.yaml"

    - shell: bash
      run: |
        pnpm env use --global 20
        pnpm install -g bun@latest
        pnpm install --frozen-lockfile
        pnpm build
