name: Publish

env:
  NODE_VERSION: 20.14.0
  PNPM_VERSION: 9.2.0

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version bump"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: "minor"

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: "Setup Project"
        uses: ./.github/actions/setup-project

      - name: "Quality Check"
        uses: ./.github/actions/quality-check

      - name: "Bump version"
        run: |
          npm version ${{ github.event.inputs.version }}
          git push origin main

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npm publish
