name: Publish

env:
  PNPM_VERSION: 9.2.0

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version bump"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: "minor"

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: false

# see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: "Setup Project"
        uses: ./.github/actions/setup-project

      - name: "Quality Check"
        uses: ./.github/actions/quality-check

      - name: "Bump version"
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          npm version ${{ github.event.inputs.version }}
          git push origin main --follow-tags

      - run: npm ci
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
