name: Publish

env:
  PNPM_VERSION: 9.2.0

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version bump"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: "patch"

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: false

# see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Setup Project"
        uses: ./.github/actions/setup-project

      - name: "Quality Check"
        uses: ./.github/actions/quality-check

      - name: "Set commit identity"
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"

      - name: Publish to GitHub Package Registry
        run: pnpm version-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - run: git push origin main --follow-tags
