name: Test

env:
  PNPM_VERSION: 9.2.0

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Setup Project"
        uses: ./.github/actions/setup-project

      - name: "Quality Check"
        uses: ./.github/actions/quality-check

      - name: "Build"
        run: |
          pnpm build
